#!/bin/bash
set -euo pipefail

BASHRC_FILE="$HOME/.bashrc"
GO_TMP_TARBALL=""

cleanup() {
    rm -f "$GO_TMP_TARBALL"
}
trap cleanup EXIT

if [[ $EUID -eq 0 ]]; then
    SUDO=""
else
    SUDO="sudo"
fi

$SUDO apt update -y
$SUDO apt install -y build-essential wget curl git vim pciutils

# Verify NVIDIA GPU
if ! gpu_info="$(lspci | grep -i nvidia)"; then
    echo "ERROR: No NVIDIA GPU detected" >&2
    exit 1
fi
echo "Detected NVIDIA GPU device(s):"
echo "$gpu_info"

# conda installation
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh
bash ~/Miniconda3-latest-Linux-aarch64.sh
unlink ~/Miniconda3-latest-Linux-aarch64.sh
source ~/.bashrc

# nodejs installation
NVM_VERSION="${NVM_VERSION:-v0.40.3}"
NODE_VERSION="${NODE_VERSION:-24}"
if [[ "$NVM_VERSION" == "latest" ]]; then
    NVM_VERSION="$(curl -fsSL https://api.github.com/repos/nvm-sh/nvm/releases/latest | sed -n 's/.*"tag_name":[[:space:]]*"\(v[0-9.]*\)".*/\1/p' | head -n1 || true)"
fi
if [[ -z "$NVM_VERSION" ]]; then
    echo "ERROR: Unable to resolve NVM version. Set NVM_VERSION explicitly (example: v0.40.3)." >&2
    exit 1
fi
curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh" | bash
\. "$HOME/.nvm/nvm.sh"
nvm install "$NODE_VERSION"
nvm alias default "$NODE_VERSION"

# Install Rust and crates
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "$HOME/.cargo/env"
cargo install --locked bat
cargo install bottom --locked
cargo install dua-cli
cargo install --locked dysk
cargo install exa
cargo install ripgrep
cargo install --force yazi-build

# GPU monitoring
$SUDO apt install -y fzf nvtop

# Install code agents (requires Node.js)
npm i -g @openai/codex
# Claude Code has switched from npm to native installer
curl -fsSL https://claude.ai/install.sh | bash

cat << 'EOF' > "$BASHRC_FILE"
# Generated by setup.sh
export PATH=/usr/local/cuda/bin:$PATH
. "$HOME/.cargo/env"
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin

HISTCONTROL=ignoredups:ignorespace
# append to the history file, don't overwrite it
shopt -s histappend
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000
# shell appearance
export PS1='\e[1;34m\u\e[m@\e[1;32m\h\e[m:\[\e[33m\]\w\[\e[0m\]\$ '
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
# export EDITOR='nvim' neovim configuration
# language environment variables
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
# general aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Conda initialization (portable; avoids hardcoded /home/<user> paths)
__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

# CUDA installation
export LD_LIBRARY_PATH="/usr/local/cuda/lib64"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export CUDA_INSTALL_PATH="/usr/local/cuda"

function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd < "$tmp"
    [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
    rm -f -- "$tmp"
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
EOF

echo "Setup complete. Open a new shell or run: source ~/.bashrc"
